version: "3"

# https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

services:
  nextools:
    container_name: vscode-nextools
    image: vscode-nextools
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      - $HOME/.gnupg/trustdb.gpg:/root/.gnupg/trustdb.gpg
      - ssh-agent-forward:/ssh-agent-forward
      - workspace:/workspace
      - /workspace/node_modules
    command: sleep infinity

volumes:
  workspace:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,noacl,nfsvers=3
      device: ":${PWD}"
  ssh-agent-forward:
    external: true
